name: Conditional workflow
on:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      naming: ${{ steps.stepfail.outputs.runid}}
    steps:
      - name: Wait a second
        run: |
          sleep 30

      - name: Reveal secrets
        run: |

      
      - name: Fail me
        continue-on-error: true
        id: stepfail
        run: |
          echo "runid=${{ toJson(github.run_number) }}" > $GITHUB_OUTPUT
          echo "${{ toJson(github) }}"
          exit 1

      - name: Even continue-on-error
        if: ${{ steps.stepfail.outcome == 'failure' }}
        run: |
          echo "Step failed"

      - name: If failed
        if: ${{ steps.stepfail.conclusion == 'failure' }}
        run: |
          echo "Step failed"

  cancelled:
    runs-on: ubuntu-latest
    needs: init
    if: ${{ cancelled() }}
    steps:
      - name: Print out
        run: |
          echo "The workflow was cancelled"

  failed:
    runs-on: ubuntu-latest
    needs: init
    if: ${{ failure() }}
    steps:
      - name: Print out
        run: |
          echo "Init job had failed steps"
          echo "${{ needs.init.outputs.naming }}"