name: Conditional workflow
on:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      naming: ${{ steps.stepfail.outputs.runid}}
    steps:
      - name: Wait a second
        run: |
          sleep 5

      - name: Reveal secrets
        run: |
          echo "REPOSECRET: ${{ secrets.REPOSECRET }}"
          echo "ENVSECRET: ${{ secrets.ENVSECRET }}"
          echo "REPOENV: ${{ vars.REPOENV }}"
          echo "ENVENV: ${{ vars.ENVENV }}"
      
      - name: Fail me
        continue-on-error: true
        id: stepfail
        run: |
          echo "runid=${{ toJson(github.run_number) }}" > $GITHUB_OUTPUT
          echo "${{ toJson(github) }}"
          exit 1
          /bin.asha

      - name: Fail this also
        id: otherfail
        run: exit 24
        
      - name: Even continue-on-error
        if: ${{ steps.otherfail.outcome == 'failure' }}
        run: |
          echo "Step failed"

      - name: If failed
        if: ${{ steps.otherfail.conclusion == 'failure' }}
        run: |
          echo "Step failed"

  cancelled:
    runs-on: ubuntu-latest
    needs: init
    if: ${{ cancelled() }}
    steps:
      - name: Print out
        run: |
          echo "The workflow was cancelled"

  failed:
    runs-on: ubuntu-latest
    needs: init
    if: ${{ failure() }}
    steps:
      - name: Print out
        run: |
          echo "Init job had failed steps"
          echo "${{ needs.init.outputs.naming }}"