name: First workflow
on:
    push:
        branches: ["main"]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get repo
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci
            
            - name: Run lint
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        needs: [lint]
        steps:
            - name: Get repo
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Run test
              run: npm run test
    build:
        runs-on: ubuntu-latest
        needs: [test]
        steps:
            - name: Get repo
              uses: actions/checkout@v4
            
            - name: Install dependencies
              run: npm ci

            - name: Run build
              run: npm run build
