name: First workflow
on:
    push:
        branches: ["test"]
    issue_comment: 
        types: [edited,deleted]
    issues:
        types:
          - closed
          - reopened
jobs:
    # lint:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Get repo
    #           uses: actions/checkout@v4

    #         - name: Install dependencies
    #           run: npm ci
            
    #         - name: Run lint
    #           run: npm run lint
    test:
        runs-on: ubuntu-latest
        # needs: [lint]
        steps:
            - name: Get repo
              uses: actions/checkout@v4

            # - name: Install dependencies
            #   run: npm ci

            # - name: Run test
            #   run: npm run test

            - name: List files
              run: ls -al

            - name: Output artifacts
              uses: actions/upload-artifact@v3
              with:
                name: out-afa
                path: |
                    package*
                    !package.json
                    index.html
                    src
    build:
        runs-on: ubuntu-latest
        needs: [test]
        steps:
            # - name: Get repo
            #   uses: actions/checkout@v4
            
            # - name: Install dependencies
            #   run: npm ci

            # - name: Run build
            #   run: npm run build

            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                name: out-afa

            - name: List all files
              run: | 
                ls -al