name: Matrix runs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nodejs: [12, 16, 18]
        os: [ubuntu-latest, windows-latest]
        exclude:
          - nodejs: 12
            os: ubuntu-latest
        include:
          - nodejs: 14
            os: ubuntu-latest
            npm: true
    steps:
      - name: Deploy stuff
        run: |
         echo "OS: ${{ matrix.os }}"
         echo "NodeJS: ${{ matrix.nodejs }}"
      - name: Conditional
        if: ${{ matrix.npm == "true" }}
        run: |
        echo "OS: ${{ matrix.os }}"
        echo "NodeJS: ${{ matrix.nodejs }}"
        echo "NPM: ${{ matrix.npm }}"