name: Matrix runs
on:
  push:
    branches:
      - main
jobs:
  thisismatrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nodejs: [12, 16, 18]
        os: [ubuntu-latest, windows-latest]
        include:
          - nodes: 14
            npm: true
        exclude:
          - nodes: 12
            os: ubuntu-latest
    steps:
      - name: Deploy stuff
        run: |
         echo "OS: ${{ matrix.os }}"
         echo "NodeJS: ${{ matrix.nodejs }}"
      - name: Conditional
        if: ${{ matrix.npm == true }}
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "NodeJS: ${{ matrix.nodejs }}"
          echo "NPM: ${{ matrix.npm }}"